In [1]:
# importing libraries
import numpy as np
import pandas as pd

In [2]:
# reading cafe sales data
df = pd.read_csv('/workspaces/data_cleaning_project/data/raw/Cafe Sales (1).csv')

In [3]:
# inspecting first 10 records
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,TXN_4977031,Cake,4,3,12,Cash,In-store,5/16/2023
2,TXN_4271903,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,TXN_7034554,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023
5,TXN_2602893,Smoothie,5,4,20,Credit Card,NaN,3/31/2023
6,TXN_4433211,UNKNOWN,3,3,9,ERROR,Takeaway,10/6/2023
7,TXN_6699534,Sandwich,4,4,16,Cash,UNKNOWN,10/28/2023
8,TXN_4717867,NaN,5,3,15,NaN,Takeaway,7/28/2023
9,TXN_2064365,Sandwich,5,4,20,NaN,In-store,12/31/2023

In [4]:
# checking for basic structure and data type
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [5]:
# checking if there are any duplicate records or not
sum(df.duplicated())

0

In [7]:
# checking if there are any duplicate records or not
print(f'cafe sales data contains {sum(df.duplicated())} duplicates record.')

cafe sales data contains 0 duplicates record.

In [8]:
# inspecting missing data for each column
# .isna() only states the error of NaN so the out put will not be accurate becoz in record Unknown records are also present.
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [9]:
# inspecting unique values in all column expect 'Transaction Id' coz it have 0 null values
df_cols = set(df.columns)

In [10]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='str')

In [11]:
# now we will convert df.columns into a set
set(df.columns)

{'Item',
 'Location',
 'Payment Method',
 'Price Per Unit',
 'Quantity',
 'Total Spent',
 'Transaction Date',
 'Transaction ID'}

In [13]:
# now we will do
df_cols = set(df.columns)

# we dont want transaction id so we code
exclude = {'Transaction ID'}

# in set there is property called difference(it means that you want to work on perticular columns that are not common with others) so we create df.cols as a set without transaction id 
df_cols = df_cols.difference(exclude)

df_cols

{'Item',
 'Location',
 'Payment Method',
 'Price Per Unit',
 'Quantity',
 'Total Spent',
 'Transaction Date'}

In [14]:
# now we will convert it into a list
df_cols = set(df.columns)
exclude = {'Transaction ID'}
df_cols = df_cols.difference(exclude)
df_cols = list(df_cols)

In [15]:
# now we will see df_cols
df_cols

['Price Per Unit',
 'Quantity',
 'Location',
 'Payment Method',
 'Item',
 'Total Spent',
 'Transaction Date']

In [16]:
# now we will see the unique value in all these columns at are available in df.columns
df_cols = set(df.columns)
exclude = {'Transaction ID'}
df_cols = df_cols.difference(exclude)
df_cols = list(df_cols)

for col in df_cols:
    print(f'{col}:\n{df[col].unique()}', end = '\n\n')

Price Per Unit:
<StringArray>
['2', '3', '1', '5', '4', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

Quantity:
<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

Location:
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

Payment Method:
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

Item:
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

Total Spent:
<StringArray>
[      '4',      '12',   'ERROR',      '10',      '20',       '9',      '16',
      '15',      '25',       '8',       '5',       '3',       '6',       nan,
 'UNKNOWN',       '2',       '1',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

Transaction Date:
<StringArray>
[  '9/8/2023',  '5/16/2023',  '7/19/2023',  '4/27/2023',  '6/11/2023',
  '3/31/2023',  '10/6/2023', '10/28/2023',  '7/28/2023', '12/31/2023',
 ...
   '8/1/2023',  '1/20/2023', '11/11/2023',  '2/13/2023',  '7/30/2023',
  '2/17/2023',  '5/20/2023',  '11/5/2023',  '3/27/2023',   '7/3/2023']
Length: 368, dtype: str

In [17]:
# now we need to replace these ERROR and UNKNOWN values across our data with NaN
df = df.replace(['ERROR', 'UNKNOWN'], np.nan) # to access Nan we code NumPy ie np.nan

df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,TXN_4977031,Cake,4,3,12,Cash,In-store,5/16/2023
2,TXN_4271903,Cookie,4,1,NaN,Credit Card,In-store,7/19/2023
3,TXN_7034554,Salad,2,5,10,NaN,NaN,4/27/2023
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023
5,TXN_2602893,Smoothie,5,4,20,Credit Card,NaN,3/31/2023
6,TXN_4433211,NaN,3,3,9,NaN,Takeaway,10/6/2023
7,TXN_6699534,Sandwich,4,4,16,Cash,NaN,10/28/2023
8,TXN_4717867,NaN,5,3,15,NaN,Takeaway,7/28/2023
9,TXN_2064365,Sandwich,5,4,20,NaN,In-store,12/31/2023

In [18]:
# now we will convert it into a Right DATA TYPES. AKA -> changing data types
# .astypes helps you convert a columns data type.
# NaN values cannot be contain in INT so we use Int64 which means higher position int numbers.
df['Quantity'] = df['Quantity'].astype('Int64')

In [19]:
df['Quantity'].astype('Int64')

0       2
1       4
2       4
3       2
4       2
       ..
9995    2
9996    3
9997    4
9998    3
9999    3
Name: Quantity, Length: 10000, dtype: Int64

In [20]:
# now for price per unit and total spend we need float coz that are decimal in no
df['Quantity'].astype('Int64')
df[['Price Per Unit', 'Total Spent']] = df[['Price Per Unit', 'Total Spent']].astype('float')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date']) 
# datetime object are done through pandas. coz by default PYTHON doesn't have dateTime data type, in python we have ints, float etc.
# after the changes we have to store the data into some where so we store into TRANACTION DATE.

In [21]:
# now we will check the data type to what it should be.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   Int64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 634.9 KB

In [22]:
# now we need to reinspect the missing records. AKA -> rechecking missing data after treatment
# this is our actual missing data from what we got earlier.
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.00
Item                 9.69
Quantity             4.79
Price Per Unit       5.33
Total Spent          5.02
Payment Method      31.78
Location            39.61
Transaction Date     4.60
dtype: float64

In [23]:
# dropping records where Transaction Data is missing
df.dropna(subset = ['Transaction Date'])
# here we can check at what percent our data is treated. if any person left we will re do it

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [24]:
# dropping records where Transaction Data is missing by adding df = in first
df = df.dropna(subset = ['Transaction Date'])

In [25]:
df.info() # all records are shown here

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              8613 non-null   str
 2   Quantity          9086 non-null   Int64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    6525 non-null   str
 6   Location          5761 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [26]:
# now we will see the Payment Method and Location which we cannot delete directly 
# either we can permanenetly drop these columns and save ourself from trouble or we can create a flag(as an INA 'Infromation Not Available)
# That way we can have entire 9540 records and we'll be able to say in the payment method and location that if NaN values are there we FLAG it as INA.

In [27]:
# replacing missing values in Payment Method and Location with INA(information not available)
# reason --> dropping there high volumn records would lead to significant data loss
# and inputing INA avoids bias
df[['Payment Method', 'Location']].fillna('INA')

      Payment Method  Location
0        Credit Card  Takeaway
1               Cash  In-store
2        Credit Card  In-store
3                INA       INA
4     Digital Wallet  In-store
...              ...       ...
9995             INA       INA
9996  Digital Wallet       INA
9997  Digital Wallet       INA
9998  Digital Wallet       INA
9999            Cash  In-store

[9540 rows x 2 columns]

In [28]:
# this just we do over write the code
df[['Payment Method', 'Location']] = df[['Payment Method', 'Location']].fillna('INA')

In [32]:
# now we will see the data with something i.e Mean Median or Mode.
# Mean and Median wont work in str data type. these operation are for no's only
# but Mode(most commonly accuring value) will work here.
# but the problem is that 30%/40% data are artificially generated by us which can create BIAS.
# It might look that 70% of transaction data made from UPI or 70% transaction are done in Store that means food fall is high
# But that might not be true coz we ourself filled the 30%-40% data.
# so not we can't delete it nor can fill it artificially from MODE option.
# so the only option left with us is 'FLAG' like 'INA'
# that means data is with us, artificial bias won't be created and we will have the records where the information is unavailable.

In [29]:
# now if we run the code we will see the deleting values which earlier present in diff values.
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.000000
Item                9.716981
Quantity            4.758910
Price Per Unit      5.303983
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [37]:
# now we can see the ITEM, QUANTITY, PRICE P/U, TOTAL SPENT
# we'll go with lowest first i.e QUANTITY
# quantity is a number so we can take MEAN, MEDIAN or MODE.
# so will go with MEAN and MEDIAN
# if both result same no then we can choose either.
# if diff result then choose median coz median doesn't care about outlier.

# i.e; inspecting mean and median values for Quantity.
quantity_mean, quantity_median = round(df['Quantity'].mean(), 0), round(df['Quantity'].median(), 0)

print(f'Mean Quantity: {quantity_mean}\nMedian Quantity: {quantity_median}')

Mean Quantity: 3.0
Median Quantity: 3.0

In [38]:
# since mean and median values are similar, replacing missing value in quantity with mean value
df['Quantity'] = df['Quantity'].fillna(quantity_mean)

In [39]:
# now we can see the quantity column is taken over/care by 0
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.000000
Item                9.716981
Quantity            0.000000
Price Per Unit      5.303983
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [40]:
# now we are left with ITEM = 9.716, PRICE P/U = 5.303, TOTAL SPENT = 4.989
# we'll go with replacing missing values in ITEM(item is text based in nature) with MODE value
# in text value only MODE values work but not mean and median.
df['Item'].mode()

0    Juice
Name: Item, dtype: str

In [41]:
# the above juice gave us 0 index so we need
df['Item'].mode()[0]

'Juice'

In [42]:
# now
df['Item'] = df['Item'].fillna(df['Item'].mode()[0])

In [43]:
# now we check data of Item which is taken care of by replacing 9.7 to 0.
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.000000
Item                0.000000
Quantity            0.000000
Price Per Unit      5.303983
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [44]:
# now we will go for PRICE P/U which is 5.303
# but before that we have to know price p/u will be diff for each cafes menu
# we cannot use avg, mean, median, mode it will throw error
# so we'll go with GroupBy Operation. --> means category wise.

# first we need to check how many values exist inside of rice p/u data.
# we do checking how many distinct prices exist for each Item category and how many times each price point is registered.
df.groupby('Item')['Price Per Unit'].value_counts()

Item      Price Per Unit
Cake      3.0               1031
Coffee    2.0               1069
Cookie    1.0                976
Juice     3.0               1288
          4.0                202
          2.0                116
          5.0                115
          1.0                112
          1.5                108
Salad     5.0               1035
Sandwich  4.0               1027
Smoothie  4.0                990
Tea       1.5                965
Name: count, dtype: int64

In [45]:
# by getting output value i.e; item per unit which is diff from each item
# now do you think we can calculate mean median and mode here? what does more sense?
# for first iten i.e CAKE its price p/u is always 3.0 which is always be same mean median and mode. and same for each items which have same price per unit.
# but for juice which have diff price per unit which is 3,4,2,5,1,1 whose avg/mean/median/mode will be 3 only.
# its means we can go for Median or Mode in our case.

# so we do filling missing price per unit values with the most frequent (Mode) price for each category
df.groupby('Item')['Price Per Unit'].transform(lambda x: x.fillna(x.mode()[0]))

0       2.0
1       3.0
2       1.0
3       5.0
4       2.0
       ...
9995    2.0
9996    3.0
9997    2.0
9998    1.0
9999    4.0
Name: Price Per Unit, Length: 9540, dtype: float64

In [46]:
# we'll over write the code inside of price P/U
df['Price Per Unit'] = df.groupby('Item')['Price Per Unit'].transform(lambda x: x.fillna(x.mode()[0]))

In [47]:
# now we check for Price P/U is taken care of by 0
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.000000
Item                0.000000
Quantity            0.000000
Price Per Unit      0.000000
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [52]:
# so now the only missing column is left with Total spent which is 4.989.
# Total spent is a no so we always calculated as the amt*quantity that you have ordered.

# so we do filling missing records for total spent by calculating the product of quantity times price per unit.
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

In [53]:
# now we check Total Spent is taken care of by 0
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.0
Item                0.0
Quantity            0.0
Price Per Unit      0.0
Total Spent         0.0
Payment Method      0.0
Location            0.0
Transaction Date    0.0
dtype: float64

In [56]:
# now we do storing clean data
# we will remove the index present in the data
df.to_csv('/workspaces/data_cleaning_project/data/clean/Cafe Sales (Clean).csv', index = False)